### ISSUE TITLE
🥳 🎉  v1.0.0  Release Notes 🥳 🎉 

### ISSUE THREAD

**Issue by AnalogJ** [fastenhealth/fasten-onprem#349]
# 🥳 🎉  v1.0.0  Release Notes 🥳 🎉 

- [feat] Manual Record Wizard allowing users to create encounters & associated records 
	- Wizard based, broken into multiple sections
	- Allows you to search for existing records (Practitioners, Organizations, etc) rather than re-entering the same data again and again.
	- Allows you to "add" records to an existing encounter/office visit (or create a new one)
	- Displays "automated/synced" records as locked, while manually created records can be edited.
	- Allows creating Observations/Lab Results
- [feat] updated fasten-source
	- Added patient portal links & logos for **~7000 providers**
	- Added support for **Humana**
- [feat] Added support for RTF binary file types
	- fixes #321 
- [docs] Added deprecation tags to report-medical-history-editor and eport-medical-history-explanation-of-benefit and report-medical-history-condition
- [bug] fixing modal zindex, so that stacked modals work correcly
- [bug] Fixed invalid models. 
- [bug] When app redirects to the login screen, we should close all modals
- [bug] Fixed issue with PDF files not displaying correctly
	- fixes #341 
- [feat] Added Fasten Health source to store all resources created manually
- [feat] Adding displaymodel for Encounter
- [feat] Reorganized fhir-card resources
- [feat] Create fhir-datatable resources
- [feat] Added Callout support for cards
- [feat] make sure that manually uploaded & created resources will automatically create Background Job for tracking.
- [bug] fixed broken chart when Observation missing effective date
- [bug] fixed broken images
    - fixes #353 
    - fixes https://github.com/fastenhealth/fasten-sources/issues/19
- [docs] Updated Roadmap
	- https://github.com/fastenhealth/docs/blob/main/roadmap.md 

supersedes  #293 

related https://github.com/fastenhealth/fasten-onprem/issues/60
related https://github.com/fastenhealth/fasten-onprem/issues/90
related https://github.com/fastenhealth/fasten-onprem/issues/137

---

# TODO

- [x] when selecting practitioners & organizations, we should disable rows that are already selected
- [x] in debug mode, we should remove related resources from the encounter object
- [ ] Attachment popup & file upload broken in desktop. 
- [ ] Add CSS padding between fhir-cards when listing. 
- [ ] Wizard submit button should highlight nav-pill containing broken form entries. 
- [ ] Add Attachment should be a button-group
- [x] Add placeholder text /notification alert for Lab Results panel. 
- [ ] Identifiers for new resources should be in the format `NEW/<RESOURCE_ID>`
- [ ] When creating sources using wizard, SOURCE_ID should be tied to USER_ID
- [x] NPI number tag doest update correctly when changing selected practitioner in AddPractitioner modal
- [x] Explore page is broken for Fasten Health source, summary endpoint fails with 500
- [ ] when unable to find the user, we should return 401 error code so that the SPA redirects to login. 
- [x] On Create Condition page, success closes Wizard, showing a blank page. 
- [x] Add Background Job when processing manual file uploads
- [ ] Flush/Truncate the database WAL on app shutdown. 
	- `PRAGMA wal_checkpoint(TRUNCATE);` 
- [ ] Add loading spinner to sources page 
- [ ] Encounters created manually have empty fhir-datagrid rows
- [ ]  `TypeError: null is not a non-null object` for AddressMode `.line`

<img width="1171" alt="Screen Shot 2023-11-26 at 5 41 08 PM" src="https://github.com/fastenhealth/fasten-onprem/assets/891875/ecd14012-d60a-4f8c-8ae6-3396535b11ee">
<img width="1157" alt="Screen Shot 2023-11-30 at 7 40 37 PM" src="https://github.com/fastenhealth/fasten-onprem/assets/891875/47bb3cac-2113-45d1-b3b1-5eaeecadd218">
<img width="1193" alt="Screen Shot 2023-11-30 at 7 40 26 PM" src="https://github.com/fastenhealth/fasten-onprem/assets/891875/417b473c-34fb-4cd1-a473-9bf19698dca8">
<img width="1149" alt="Screen Shot 2023-11-30 at 7 40 20 PM" src="https://github.com/fastenhealth/fasten-onprem/assets/891875/2d61de46-2bb1-4644-8cdc-b435fddf00a1">
<img width="1155" alt="Screen Shot 2023-11-30 at 7 40 12 PM" src="https://github.com/fastenhealth/fasten-onprem/assets/891875/fe5cf3c3-7a24-4451-96f7-5beda56963b4">
<img width="1156" alt="Screen Shot 2023-11-30 at 7 39 58 PM" src="https://github.com/fastenhealth/fasten-onprem/assets/891875/9e39be1f-3288-4d12-823d-91dc84dbda3b">
<img width="818" alt="Screen Shot 2023-12-07 at 2 27 28 PM" src="https://github.com/fastenhealth/fasten-onprem/assets/891875/5a76fcbf-db3a-4165-b305-ed6ddc03fdda">
<img width="814" alt="Screen Shot 2023-12-07 at 2 27 04 PM" src="https://github.com/fastenhealth/fasten-onprem/assets/891875/4581507a-ee6d-45dd-a5f6-3a317bab5af1">
